repos:
-   repo: local
    hooks:
    -   id: swiftlint
        name: SwiftLint
        entry: swiftlint --strict
        language: system
        types: [swift]
        pass_filenames: true

    -   id: swiftformat
        name: SwiftFormat
        entry: swiftformat
        language: system
        types: [swift]
        pass_filenames: true

    -   id: xcode-test
        name: Run Xcode Tests
        entry: bash -c 'export DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer" && 
                     xcrun simctl shutdown all &&
                     xcodebuild test -scheme "OneTwo" -destination "platform=iOS Simulator,name=iPhone 16 Plus" -testPlan "OneTwoTests" || 
                     (echo "Tests failed. Please fix before committing." && exit 1)'
        language: system
        pass_filenames: false
        types: [swift]
