repos:
-   repo: local
    hooks:
    -   id: swiftlint
        name: SwiftLint
        entry: swiftlint --strict --fix
        language: system
        types: [swift]
        pass_filenames: true

    -   id: swiftformat
        name: SwiftFormat
        entry: swiftformat
        language: system
        types: [swift]
        pass_filenames: true
