name: iOS Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**.swift'
      - '**.xcodeproj/**'
      - '**.xcworkspace/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.swift'
      - '**.xcodeproj/**'
      - '**.xcworkspace/**'

jobs:
  test:
    name: Build and Test
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: List Available Simulators
      run: xcrun simctl list devices

    - name: Install xcpretty
      run: gem install xcpretty
      
    - name: Build and Test
      run: |
        xcodebuild test \
          -scheme "OneTwo" \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1" \
          -skipPackagePluginValidation \
          | xcpretty && exit ${PIPESTATUS[0]}
          
    - name: Run Test Coverage
      run: |
        xcodebuild test \
          -scheme "OneTwo" \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1" \
          -enableCodeCoverage YES \
          | xcpretty && exit ${PIPESTATUS[0]}
